### ISSUE TITLE
Unhandled promise rejection

### ISSUE THREAD

**Issue by thevalyreangroup** [jimhigson/ring-api#7]
I'm using your library for a node-red embedded object. https://github.com/thevalyreangroup/node-red-contrib-ringdoorbell

A couple weeks ago Ring updated their authentication methods, which i see you caught and changed to use the new token system. However, i'm still getting this error after updating to your new code with v 2.1.3

Unfortunately i can't see where in your code this is being caught. Any ideas?

```
(node:12152) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: problem getting token for user tony@thevalyreangroup.com Request failed with status code 401 :: Error: Request failed with status code 401
    at createError (C:\Users\Administrator\node_modules\axios\lib\core\createError.js:16:15)
    at settle (C:\Users\Administrator\node_modules\axios\lib\core\settle.js:18:12)
    at IncomingMessage.handleStreamEnd (C:\Users\Administrator\node_modules\axios\lib\adapters\http.js:192:11)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1055:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
---try/catch/throw---
```

**Comment by jimhigson** [comment]
Can you try running with the debug environment variable set to ‘ring-api’ and see if you get any more informative logging? It should tell you exactly what is being POSTed that way

**Comment by jimhigson** [comment]
new section in README on debugging: 

https://github.com/jimhigson/ring-api/commit/9a19d51fba0aad6a5834db61c0cd3dfdaa354b69

**Comment by jimhigson** [comment]
Have improved the error reporting in a new version just published to npm. Note that this required the API creation to be async so bumped the semver up to 3.0.0

**Comment by thevalyreangroup** [comment]
Thanks, that all helped me to find the issue.
